baseURL=http://dev01.hq.smartfabric.ch:7000
baseURLGUI=http://dev01.hq.smartfabric.ch:9000
baseURLDocuments=http://dev01.hq.smartfabric.ch:9901
baseURLCatalogs=http://dev01.hq.smartfabric.ch:7050
baseURLEngine=http://dev01.hq.smartfabric.ch:8080
